config/routes.rb
Rails.application.routes.draw do

  get 'to_do_lists/:list_id/to_do_items' => 'to_do_items#index', as: :to_do_items_show

  get 'to_do_lists/:list_id/to_do_items/new' => 'to_do_items#new', as: :new_to_do_items

  get 'to_do_lists/:list_id/to_do_items/:id/edit' => 'to_do_items#edit', as: :edit_to_do_items

  resources :to_do_items

  resources :to_do_lists

  root 'to_do_lists#index'

end

app/models/to_do_item.rb
class ToDoItem < ActiveRecord::Base

  belongs_to :to_do_list

end

app/models/to_do_list.rb
class ToDoList < ActiveRecord::Base

  has_many :to_do_items

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/to_do_items_controller.rb
class ToDoItemsController < ApplicationController
  before_action :set_to_do_item, only: [:show, :edit, :update, :destroy]

  # GET /to_do_items
  # GET /to_do_items.json
  def index
    @to_do_items = ToDoItem.where(:list_id => params[:list_id])
  end

  # GET /to_do_items/1
  # GET /to_do_items/1.json
  def show
  end

  # GET /to_do_items/new
  def new
    @to_do_item = ToDoItem.new
  end

  # GET /to_do_items/1/edit
  def edit
  end

  # POST /to_do_items
  # POST /to_do_items.json
  def create
    @to_do_item = ToDoItem.new(to_do_item_params)
    respond_to do |format|
      if @to_do_item.save
        format.html { redirect_to @to_do_item, notice: 'To do item was successfully created.' }
        format.json { render :show, status: :created, location: @to_do_item }
      else
        format.html { render :new }
        format.json { render json: @to_do_item.errors, status: :unprocessable_entity }
      end
    end
  end

  def move_lower

  end

  def move_higher

  end

  # PATCH/PUT /to_do_items/1
  # PATCH/PUT /to_do_items/1.json
  def update
    respond_to do |format|
      if @to_do_item.update(to_do_item_params)
        format.html { redirect_to @to_do_item, notice: 'To do item was successfully updated.' }
        format.json { render :show, status: :ok, location: @to_do_item }
      else
        format.html { render :edit }
        format.json { render json: @to_do_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /to_do_items/1
  # DELETE /to_do_items/1.json
  def destroy
    @to_do_item.destroy
    respond_to do |format|
      format.html { redirect_to to_do_lists_path, notice: 'To do item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_to_do_item
      @to_do_item = ToDoItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def to_do_item_params
      params.require(:to_do_item).permit(:name, :list_id, :position)
    end
end

app/controllers/to_do_lists_controller.rb
class ToDoListsController < ApplicationController
  before_action :set_to_do_list, only: [:show, :edit, :update, :destroy]

  # GET /to_do_lists
  # GET /to_do_lists.json
  def index
    @to_do_lists = ToDoList.all
  end

  # GET /to_do_lists/1
  # GET /to_do_lists/1.json
  def show
  end

  # GET /to_do_lists/new
  def new
    @to_do_list = ToDoList.new
  end

  # GET /to_do_lists/1/edit
  def edit
  end

  # POST /to_do_lists
  # POST /to_do_lists.json
  def create
    @to_do_list = ToDoList.new(to_do_list_params)

    respond_to do |format|
      if @to_do_list.save
        format.html { redirect_to @to_do_list, notice: 'To do list was successfully created.' }
        format.json { render :show, status: :created, location: @to_do_list }
      else
        format.html { render :new }
        format.json { render json: @to_do_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /to_do_lists/1
  # PATCH/PUT /to_do_lists/1.json
  def update
    respond_to do |format|
      if @to_do_list.update(to_do_list_params)
        format.html { redirect_to @to_do_list, notice: 'To do list was successfully updated.' }
        format.json { render :show, status: :ok, location: @to_do_list }
      else
        format.html { render :edit }
        format.json { render json: @to_do_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /to_do_lists/1
  # DELETE /to_do_lists/1.json
  def destroy
    @to_do_list.destroy
    respond_to do |format|
      format.html { redirect_to to_do_lists_url, notice: 'To do list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_to_do_list
      @to_do_list = ToDoList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def to_do_list_params
      params.require(:to_do_list).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/to_do_items_helper.rb
module ToDoItemsHelper
end

app/helpers/to_do_lists_helper.rb
module ToDoListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShoppingList</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/to_do_items/_form.html.erb
<%= form_for @to_do_item, :html => { :class => "form-horizontal to_do_item" } do |f| %>
    <% if @to_do_item.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@to_do_item.errors.count, "error") %> prohibited this to_do_item from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @to_do_item.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%= error_span(@to_do_item[:name]) %>
  </div>

    <div class="control-group">
      <div class="controls">
        <%= f.hidden_field :list_id, :value => params[:list_id]%>
      </div>
      <%= error_span(@to_do_item[:list_id]) %>
    </div>

    <div class="control-group">
      <%= f.label :position, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :position, :class => 'form-control' %>
      </div>
      <%= error_span(@to_do_item[:position]) %>
    </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
              to_do_items_show_url(params[:list_id]), :class => 'btn btn-default' %>

<% end %>

app/views/to_do_items/edit.html.erb
<%- model_class = ToDoItem -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/to_do_items/index.html.erb
<%- model_class = ToDoItem -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:list_id) %></th>
      <th><%= model_class.human_attribute_name(:position) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @to_do_items.each do |to_do_item| %>
           <tr>
        <td><%= link_to to_do_item.id, to_do_item_path(to_do_item) %></td>
        <td><%= to_do_item.name %></td>
        <td><%= to_do_item.list_id %></td>
        <td><%= to_do_item.position %></td>
        <td><%=l to_do_item.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_to_do_items_url(params[:list_id], to_do_item.id),
                      :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      to_do_item_path(to_do_item),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
          <%= link_to t('.move_higher', :default => "Move up"),
                      to_do_items_path,
                      :method => :move_higher,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.move_lower', :default => "Move down"),
                      to_do_items_path,
                      :method => :move_lower,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-default btn-xs' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.index', :default => 'See lists'),
            to_do_lists_path,
            :class => 'btn btn-primary' %>
<%= link_to t('.new', :default => 'New item'),
            new_to_do_item_url(params),
            :class => 'btn btn-primary'%>

app/views/to_do_items/new.html.erb
<%- model_class = ToDoItem -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/to_do_items/show.html.erb
<%- model_class = ToDoItem -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @to_do_item.name %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              to_do_lists_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_to_do_item_path(@to_do_item), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              to_do_item_path(@to_do_item),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/to_do_lists/_form.html.erb
<%= form_for @to_do_list, :html => { :class => "form-horizontal to_do_list" } do |f| %>

    <% if @to_do_list.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@to_do_list.errors.count, "error") %> prohibited this to_do_list from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @to_do_list.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%= error_span(@to_do_list[:name]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            to_do_lists_path, :class => 'btn btn-default' %>

<% end %>

app/views/to_do_lists/edit.html.erb
<%- model_class = ToDoList -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/to_do_lists/index.html.erb
<%- model_class = ToDoList -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @to_do_lists.each do |to_do_list| %>
      <tr>
        <td><%= link_to to_do_list.id, to_do_list_path(to_do_list) %></td>
        <td><%= to_do_list.name %></td>
        <td><%=l to_do_list.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_to_do_list_path(to_do_list), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      to_do_list_path(to_do_list),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
          <%= link_to t('.index', :default => 'See items in list'),
                      to_do_items_show_url(to_do_list.id),
                      :class => 'btn btn-default btn-xs' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => 'New list'),
            new_to_do_list_path,
            :class => 'btn btn-primary' %>

app/views/to_do_lists/new.html.erb
<%- model_class = ToDoList -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/to_do_lists/show.html.erb
<%- model_class = ToDoList -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @to_do_list.name %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              to_do_lists_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_to_do_list_path(@to_do_list), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              to_do_list_path(@to_do_list),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>